{"Name":"experiment",
 "Description":"Silly rules with conditions.",
 "Parameters":{"DoorLock":"doorLock",
               "Light":"light",
	       "MotionSensor":"motionSensor"},
 "Facts":{"likes":{"likes":"tacos"},
	  "wants":{"wants":"chips","at":["home","office"]},
	  "father":{"father":"homer"},
	  "mother":{"mother":"marge"}},
 "Rules":{"r1":{"when":{"pattern":{"state":"unlocked",
				   "device":"DoorLock"}},
		"condition":{"pattern":{"likes":"?likes"}},
                "action":{"code":["console.log('for ACCOUNT, turn light Light on to see ' + likes);",
				  "Env.http('GET', 'http://ENDPOINT/' + 'Light' + '/on');"]}},
	  "r2":{"when":{"pattern":{"state":"unlocked",
				   "device":"MotionSensor"}},
		"condition":{"pattern":{"likes":"?likes"}},
                "action":{"code":"Env.http('GET', 'http://ENDPOINT/' + 'Light' + '/strobe');"}},
	  "r3":{"when":{"pattern":{"signal":"?x"}},
		"condition":{"pattern":{"father":"?father"}},
		"action":{"code":"Env.http('GET', 'http://ENDPOINT/' + father + '/alien/' + x);"}}}}
