{"Name":"experiment",
 "Description":"More silly rules with conditions.",
 "Parameters":{"DoorLock":"doorLock",
               "Light":"light",
	       "MotionSensor":"motionSensor"},
 "Facts":{"likes":{"likes":"tacos","who":"homer"},
	  "wants":{"wants":"chips","at":["home","office"]},
	  "father":{"father":"homer"},
	  "mother":{"mother":"marge"}},
 "Rules":{"r1":{"when":{"pattern":{"state":"unlocked",
				   "device":"DoorLock"}},
		"condition":{"pattern":{"likes":"?likes"}},
                "action":{"code":["console.log('for ACCOUNT, turn light Light on to see ' + likes);",
				  "Env.http('GET', 'http://ENDPOINT/' + 'Light' + '/on?tx=' + Env.TxId);"]}},
	  "r2":{"when":{"pattern":{"state":"motion",
				   "device":"MotionSensor"}},
		"condition":{"pattern":{"likes":"?likes"}},
                "action":{"code":"Env.http('GET', 'http://ENDPOINT/' + 'Light' + '/strobe?tx=' + Env.TxId);"}},
	  "r3":{"when":{"pattern":{"state":"noMotion",
				   "device":"MotionSensor"}},
		"condition":{"and": [{"pattern":{"likes":"?likes","who":"?somebody"}},
                                     {"pattern":{"father":"?somebody"}}]},
                "action":{"code":"Env.http('GET', 'http://ENDPOINT/' + 'Light' + '/flash?tx=' + Env.TxId);"}},
	  "r4":{"when":{"pattern":{"signal":"?x"}},
		"condition":{"pattern":{"father":"?father"}},
		"action":{"code":"Env.http('GET', 'http://ENDPOINT/' + father + '/alien/' + x + '?tx=' + Env.TxId);"}}}}
